/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components/button': RouteRecordInfo<
      '/components/button',
      '/components/button',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components/card': RouteRecordInfo<
      '/components/card',
      '/components/card',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components/dialog': RouteRecordInfo<
      '/components/dialog',
      '/components/dialog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components/form': RouteRecordInfo<
      '/components/form',
      '/components/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components/input': RouteRecordInfo<
      '/components/input',
      '/components/input',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components/select': RouteRecordInfo<
      '/components/select',
      '/components/select',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components/slider': RouteRecordInfo<
      '/components/slider',
      '/components/slider',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components/toggle': RouteRecordInfo<
      '/components/toggle',
      '/components/toggle',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/components/tooltip': RouteRecordInfo<
      '/components/tooltip',
      '/components/tooltip',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/themes': RouteRecordInfo<
      '/themes',
      '/themes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/components/button.vue': {
      routes:
        | '/components/button'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/components/card.vue': {
      routes:
        | '/components/card'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/components/dialog.vue': {
      routes:
        | '/components/dialog'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/components/form.vue': {
      routes:
        | '/components/form'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/components/input.vue': {
      routes:
        | '/components/input'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/components/select.vue': {
      routes:
        | '/components/select'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/components/slider.vue': {
      routes:
        | '/components/slider'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/components/toggle.vue': {
      routes:
        | '/components/toggle'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/components/tooltip.vue': {
      routes:
        | '/components/tooltip'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/themes.vue': {
      routes:
        | '/themes'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
