[workspace.package]
edition = "2024"

[workspace]
members = [
    "crates/api/tak-server-api",
    "crates/api/tak-server-api-contract",
    "crates/infra/tak-auth-ory",
    "crates/infra/tak-bot-registry",
    "crates/infra/tak-email-lettre",
    "crates/infra/tak-events-google-sheets",
    "crates/infra/tak-persistence-profile-pictures",
    "crates/infra/tak-persistence-sea-orm",
    "crates/infra/tak-persistence-sea-orm-entities",
    "crates/infra/tak-persistence-sea-orm-migrations",
    "crates/infra/tak-player-connection",
    "crates/more-concurrent-maps",
    "crates/tak-bot-tei-bridge",
    "crates/tak-core",
    "crates/tak-main",
    "crates/tak-server-app",
]
resolver = "3"

[profile.release-wasm]
inherits = "release"
lto      = true
