POST http://localhost:9999/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "password"
}

###

POST http://localhost:9999/v3/seek/add
Content-Type: application/json
Authorization: Bearer <token>

{
    "seek": {
        "color": "random",
        "tournament": false,
        "unrated": true,
        "half_komi": 0,
        "board_size": 5,
        "reserve_pieces": 5,
        "reserve_capstones": 1,
        "time_ms": 300000,
        "increment_ms": 0,
        "extra_move": 5,
        "extra_time_ms": 60000,
        "opponent": "null"
    }
}

###

DELETE http://localhost:9999/v3/seek
Authorization: Bearer <token>
