/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/(auth)/login': RouteRecordInfo<
      '/(auth)/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(auth)/recover': RouteRecordInfo<
      '/(auth)/recover',
      '/recover',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(auth)/register': RouteRecordInfo<
      '/(auth)/register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(auth)/verify': RouteRecordInfo<
      '/(auth)/verify',
      '/verify',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/account': RouteRecordInfo<
      '/account',
      '/account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/analysis': RouteRecordInfo<
      '/analysis',
      '/analysis',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/community': RouteRecordInfo<
      '/community',
      '/community',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/leaderboard': RouteRecordInfo<
      '/leaderboard',
      '/leaderboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/match.[id]': RouteRecordInfo<
      '/match.[id]',
      '/match/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/online.[id]': RouteRecordInfo<
      '/online.[id]',
      '/online/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/play': RouteRecordInfo<
      '/play',
      '/play',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/player.[id]': RouteRecordInfo<
      '/player.[id]',
      '/player/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/puzzle': RouteRecordInfo<
      '/puzzle',
      '/puzzle',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tournaments/': RouteRecordInfo<
      '/tournaments/',
      '/tournaments',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tournaments/[id]': RouteRecordInfo<
      '/tournaments/[id]',
      '/tournaments/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/watch': RouteRecordInfo<
      '/watch',
      '/watch',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(auth)/login.vue': {
      routes:
        | '/(auth)/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(auth)/recover.vue': {
      routes:
        | '/(auth)/recover'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(auth)/register.vue': {
      routes:
        | '/(auth)/register'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(auth)/verify.vue': {
      routes:
        | '/(auth)/verify'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/account.vue': {
      routes:
        | '/account'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/analysis.vue': {
      routes:
        | '/analysis'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/community.vue': {
      routes:
        | '/community'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/leaderboard.vue': {
      routes:
        | '/leaderboard'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/match.[id].vue': {
      routes:
        | '/match.[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/online.[id].vue': {
      routes:
        | '/online.[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/play.vue': {
      routes:
        | '/play'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/player.[id].vue': {
      routes:
        | '/player.[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/puzzle.vue': {
      routes:
        | '/puzzle'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings.vue': {
      routes:
        | '/settings'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tournaments/index.vue': {
      routes:
        | '/tournaments/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tournaments/[id].vue': {
      routes:
        | '/tournaments/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/watch.vue': {
      routes:
        | '/watch'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
